### ISSUE TITLE
Implement an 'apt-get' system.

### ISSUE THREAD

**Issue by Shuudoushi** [Shuudoushi/OpenOS_Plus#32]
Include things like 'install' for optional packages and have 'update' also run through 'apt-get'. I will likely need help and quite a bit of extra help with this though, as I'm sure it's not going to be as easy I think...

**Comment by Shuudoushi** [comment]
There is enough systems out there for doing what apt-get can do (oppm and mpt to name a couple).

**Comment by SuPeRMiNoR2** [comment]
Whattt? why don't you just create a new one, then it can be a standard! https://xkcd.com/927/

**Comment by Shuudoushi** [comment]
Or I could just rename wget and BREAK ALL THE THINGS!!!
