### ISSUE TITLE
Question / Suggestion

### ISSUE THREAD

**Issue by brisingraerowing** [Shuudoushi/OpenOS_Plus#64]
Question: What OpenOS version is SecureOS based on?

Suggestion: As OpenSecurity is being ported to 1.10.2, maybe SecureOS can be updated to use the latest 1.6 OpenOS code (if needed).

**Comment by payonel** [comment]
maybe this'll do https://github.com/Shuudoushi/SecureOS/pull/66

**Comment by payonel** [comment]
or https://github.com/Shuudoushi/SecureOS/pull/68 might be better, for the dev branch
