### ISSUE TITLE
Error with Installer.

### ISSUE THREAD

**Issue by eawilhelm** [Shuudoushi/OpenOS_Plus#71]
Hey, I'm not a scripter by any means so I'm lost when I see errors. This showed up when running the fixed Installer.lua. 

![error](https://user-images.githubusercontent.com/36146873/44694905-5bd24000-aa3e-11e8-9d29-6d09c9ae3566.png)

**Comment by crazybrain23** [comment]
Did you get it from the raw file and not the html? [Found here](https://raw.githubusercontent.com/Shuudoushi/SecureOS/release/installer.lua)
