### ISSUE TITLE
Module auth not found

### ISSUE THREAD

**Issue by RedSpeeds** [Shuudoushi/OpenOS_Plus#72]
Hi when i run the installer i cant continue since it cannot find module auth
please fix

**Comment by Aeris1One** [comment]
Same

**Comment by CaitlynMainer** [comment]
This repository hasn't been updated in 2 years.  My last contact with Shuudoushi was about 6 months ago at this point, and he stated he didn't have a computer.  I would treat this as abandonware at this point, and move on.
